# ============================================
# wrangler.toml — training-02
# Static site frontend untuk Training Rencana Zonasi
# Kabupaten Luwu, Sulawesi Selatan
# ============================================
name = "training-02"
compatibility_date = "2026-06-29"
assets = { directory = "." }
routes = ["latih-02.wanantara.org/*"]
